# Required environment variables (set these in CircleCI):
# DOCKER_LOGIN - Dockerhub service account username
# DOCKER_PASSWORD - Dockerhub service account password

version: 2.1

setup: true

orbs:
  node: circleci/node@1.1.6
  docker: circleci/docker@1.3.0
  circleci: circleci/circleci-cli@0.1.9
  rnikkei-yq: nikkei/rnikkei-yq@0.0.3
  continuation: circleci/continuation@0.1.2

jobs:
  setup:
    executor: continuation/default
    steps:
      - checkout
      - circleci/install
      - rnikkei-yq/install:
          version: v4.6.0
      - run:
          name: Validate orb.yaml
          command: circleci orb validate .circleci/orb.yml
      - run:
          name: Generate config
          command: ./scripts/generate_config.sh > generated_config.yml
      - continuation/continue:
          configuration_path: ./.circleci/generated_config.yml

workflows:
  setup:
    jobs:
      - setup:
          filters: # run for all branches AND tags
            tags:
              only: /.*/
